module ActiveMerchant
  module Billing
    module TelemoneyCodes

      #Telemoney Transaction Response Codes
      TM_ERROR_CODES = {
        # "0"       =>  "TRANSACTION FAILED – Transaction is not processed by payment gateway",
        # "20"      =>  "TRANSACTION FAILED – Error in communication with local server".
        # "9201"    =>  "TRANSACTION FAILED – Your default payment type is not on the list of accepted payment types by the merchant.",
        # "9202"    =>  "TRANSACTION FAILED – System timeout. Please repeat the transaction.".
        # "9203"    =>  "TRANSACTION FAILED – Cancelled by user. If you are having problems with the transaction",
        # "9204"    =>  "TRANSACTION FAILED – PIN not verified. If you are having problems with the transaction",
        # "9205"    =>  "TRANSACTION FAILED – Call not accepted. If you are having problems with the transaction",
        # "9206"    =>  "TRANSACTION FAILED – Unable to contact mobile phone. If you are having problems with the transaction",
        # "9209"    =>  "INVALID ACCOUNT – The TeleMoney number you entered is not valid. Please check your number and try again. If you continue to have problems with the transaction",
        # "9210"    =>  "Due to network problems, we are unable to continue with the purchase. Please try again. If you are still having problems with the transaction, please call the following :Singapore Hotline : +65 8989090Malaysia Hotline : +60 (3) 8996 5655 or email help@telemoney.com.sg. Message reference #9210",
        # "9213"    =>  "TRANSACTION FAILED – This transaction has been rejected because the payment details message received by TeleMoney contains incomplete or invalid data. Message reference #9213",
        # "9214"    =>  "TRANSACTION FAILED – This transaction did not complete due to network problems. Please try again at a later time. Message reference # 9214If continue having problems with this transaction",
        # "9215"    =>  "TRANSACTION FAILED – This transaction did not complete due to network problems. Please try again at a later time. Message reference # 9215If continue having problems with this transaction",
        # "9216"    =>  "PAYMENT AUTHORIZATION DECLINED – This transaction was not approved because the bank has not authorized the payment. Message reference #9216",
        # "9217"    =>  "TRANSACTION FAILED – This transaction was not approved because the card used has expired OR the expiry date is wrong. Message reference #9217",
        # "9218"    =>  "TRANSACTION FAILED – This transaction was not approved because currently system is under maintenance. Please contact the merchant for the details.",
        # "9219"    =>  "TRANSACTION FAILED – This transaction was not approved because the merchant registration status is awaiting confirmation. Message reference #9219",
        # "9220"    =>  "TRANSACTION FAILED – This transaction was rejected because the merchant is not registered with TeleMoney. Message reference #9220",
        # "9223"    =>  "TRANSACTION FAILED. Payment Server under scheduled maintenance. We apologize for the inconvenience.",
        # "9224"    =>  "TRANSACTION FAILED. This Merchant does not register as AMEX Merchant.",
        # "9225"    =>  "TRANSACTION FAILED. Network failure. Message reference #9225",
        # "9226"    =>  "TRANSACTION FAILED. Invalid response from gateway. Message reference #9226",
        # "9227"    =>  "TRANSACTION FAILED – Thank you for using our payment gateway unfortunately we are unable to process your payment now. Please try again. If you are still having problems with the transaction",
        # "9230"    =>  "TRANSACTION FAILED –This transaction has been rejected because the Modus card can be only used for TeleMoney transaction under “TeleMoney-Protected Payments via Mobile Phone” (Please look for the Modus logo.)If you are having problems with the transaction",
        # "9231"    =>  "PAYMENT AUTHORIZATION DECLINED – This transaction was not approved because the bank has not authorized the payment. Message reference #9231",
        # "9240"    =>  "Due to network problems, we are unable to continue with the purchase. Please try again. Message reference #9240",
        # "9266"    =>  "The transaction been rejected by bank. Please check the bank response code from response string or merchant lobby.",
        # "9300"    =>  "INVALID ENTRY – The Expiry Date entry has either expired or is not of a valid format. For example an expiry of July 2002 would be entered as 07 02. Please try again. Message reference # 9300",
        # "9301"    =>  "INVALID ENTRY – The Credit/Charge Card number entered is not valid. Please check that you have entered only numbers without any spaces or other characters. Please try again. Message reference # 9301",
        # "9302"    =>  "INVALID ENTRY – The Credit/Charge Card number entered is not valid. Please check that you have entered only numbers without any spaces or other characters. Please try again. Message reference # 9302",
        # "9303"    =>  "INCOMPLETE FORM – Please complete all mandatory entries in the form. Message reference # 9303",
        # "9304"    =>  "REPEATED SUBMISSION DETECTED – The same transaction has already been submitted.",
        # "9503"    =>  "TRANSACTION FAILED - The transaction type is not valid for the transaction. Message reference #9503",
        # "9504"    =>  "Please retain this email for your record. If you need any clarification",
        # "9505"    =>  "TRANSACTION FAILED - This transaction was rejected because the Merchant Ref is Not Similiar On PaymentURL call. Message reference #9505",
        # "9506"    =>  "TRANSACTION FAILED - This transaction was rejected because the Merchant Ref is Already Used. Message reference #9506",
        # "9507"    => "TRANSACTION FAILED - This transaction was rejected because the Debit Amount Structure is Incorrect. Message reference #9507",
        # "9508"    => "TRANSACTION FAILED - This transaction was rejected because the Currency Type is Not Supported. Message reference #9508",
        # "9509"    => "TRANSACTION FAILED - This transaction was rejected because the Merchant is Not A MOTO Merchant. Message reference #9509",
        # "9510"    => "TRANSACTION FAILED - Sorry this service is opened to local TeleMoney members only.",
        # "9511"    => "TRANSACTION FAILED - This transaction was rejected because the Merchant does not support payment by eNets. Message reference #9511",
        # "9512"    => "TRANSACTION FAILED - This transaction was rejected because the amount is over the maximum limited allowed by the merchant for eNets. Message reference #9512",
        # "9513"    => "TRANSACTION FAILED - This transaction was rejected because eNets does not support zero dollar transaction. Message reference #9513" ,
        # "9516"    => "TRANSACTION FAILED - Transacted amount over maximum stored value transaction limit. Message reference #9516",
        # "9517"    => "INVALID ENTRY - Please enter your stored value account number. Message reference # 9517",
        # "9519"    => "TRANSACTION FAILED - Stored value transaction does not support zero dollar amount. Message reference #9519" ,
        # "9520"    => "TRANSACTION FAILED - This transaction was rejected because of validation error. Message reference #9520",
        # "9521"    => "TRANSACTION FAILED - This transaction was rejected because the stored value account is invalid. For assistance ",
        # "9522"    => "TRANSACTION FAILED - This transaction did not complete due to network problems. Please try again at a later time. Message reference # 9522If continue having problems with this transaction",
        # "9523"    => "TRANSACTION FAILED - This transaction did not complete due to network problems. Please try again at a later time. Message reference # 9523If continue having problems with this transaction",
        # "9524"    => "TRANSACTION FAILED - This transaction was rejected because the amount in your stored value account is insufficient to cover this transaction. For assistance ",
        # "9525"    => "TRANSACTION FAILED - This transaction was rejected because the stored value account is invalid. For assistance ",
        # "9526"    => "REGISTRATION FAILED - Stored value account already exist. Message reference #9526",
        # "9528"    => "TRANSACTION FAILED - Your request for withdrawal has failed due to invalid StoredValue account status. For assistance",
        # "9600"    => "TRANSACTION FAILED - This transaction was rejected because the Credit Card limit has been exceeded. Message reference #9600",
        # "9601"    => "TRANSACTION FAILED - This transaction was rejected because of Timeout at Merchant end. Message reference #9601 ",
        # "9609"    => "TRANSACTION FAILED - This transaction was rejected because the transacted amount is over the limit accepted by the merchant. Message reference #9609 ",
        # "9651"    => "TRANSACTION FAILED : Merchant NOT SENTINEL enabled Exception Message #: 9651 ",
        # "9652"    => "TRANSACTION FAILED : Telemoney Amount Usage Limit Exceeded Message #: 9652 ",
        # "9653"    => "TRANSACTION FAILED : Telemoney Usage Limit Exceeded Message #: 9653",
        # "9654"    => "TRANSACTION FAILED : Credit Card Amount Usage Limit Exceeded Message #: 9654 ",
        # "9655"    => "TRANSACTION FAILED : Credit Card Usage Limit Exceeded Message #: 9655",
        # "9658"    => "TRANSACTION FAILED : IP Address Usage Limit Exceeded Message #: 9658 ",
        # "9659"    => "TRANSACTION FAILED : IP Address Fail Usage Limit Exceeded Message #: 9659",
        # "9660"    => "PAYMENT AUTHORIZATION DECLINED - This transaction was not approved because the bank has not authorized the payment. For help ",
        # "9701"    => "REQUEST FAILED - The Order Number requested does not exist.",
        # "9702"    => "REQUEST FAILED - Information supplied for clearing the Order Number does not match the database. ",
        # "9703"    => "REQUEST FAILED - The Order Number requested is a failed transaction. ",
        # "9704"    => "REQUEST FAILED - The Order Number requested has already been cleared.",
        # "9705"    => "REQUEST FAILED - ""No confirmation from merchant's server.",
        # "9750"    => "TRANSACTION FAILED - CAPTURE amount exceeds initial AUTH amount. ",
        # "9751"    => "TRANSACTION FAILED - CAPTURE on non-successful AUTH transaction. ",
        # "9752"    => "TRANSACTION FAILED – Invalid Transaction Type. ",
        # "9753"    => "TRANSACTION FAILED – Invalid Sub Transaction Type. ",
        # "9754"    => "TRANSACTION FAILED – Missing Sub Transaction Type. ",
        # "AUTF"    => "AUTHENTICATION FAILED. The authentication information you provided does not match the records for this Visa/Master card. To ensure the highest level of security, this Visa/Master card cannot be used to complete this purchase.",
        # "AUTF_A"  => "AUTHENTICATION FAILED due to connection failure. Please try again later. ",
        # "AUTF_N"  => "AUTHENTICATION FAILED. The authentication information you provided does not match the records for this Visa/Master card. To ensure the highest level of security, this Visa/Master card cannot be used to complete this purchase.",
        # "AUTF_U"  => "AUTHENTICATION FAILED as your credit card does not participate VISA 3D Security or MasterCard SecureCode, so please perform transaction with VISA 3D Security or MasterCard SecureCode Enabled Credit Card."
      }

      ISSUER_RESPONSE_CODES = {
        # '00' => 'Approved',
        # '01' => 'Refer to Card Issuer',
        # '02' => 'Refer to Card Issuer',
        # '03' => 'Invalid Merchant',
        # '04' => 'Pick Up Card',
        # '05' => 'Do Not Honor',
        # '07' => 'Pick Up Card',
        # '12' => 'Invalid Transaction',
        # '14' => 'Invalid Card Number (No such Number)',
        # '15' => 'No Such Issuer',
        # '33' => 'Expired Card',
        # '34' => 'Suspected Fraud',
        # '36' => 'Restricted Card',
        # '39' => 'No Credit Account',
        # '41' => 'Card Reported Lost',
        # '43' => 'Stolen Card',
        # '51' => 'Insufficient Funds',
        # '54' => 'Expired Card',
        # '57' => 'Transaction Not Permitted',
        # '59' => 'Suspected Fraud',
        # '62' => 'Restricted Card',
        # '65' => 'Exceeds withdrawal frequency limit',
        # '91' => 'Cannot Contact Issuer'
      }

      VERIFIED_3D_CODES = {
        # 'Y' => 'The cardholder was successfully authenticated.',
        # 'E' => 'The cardholder is not enrolled.',
        # 'N' => 'The cardholder was not verified.',
        # 'U' => 'The cardholder\'s Issuer was unable to authenticate due to a system error at the Issuer.',
        # 'F' => 'An error exists in the format of the request from the merchant. For example, the request did not contain all required fields, or the format of some fields was invalid.',
        # 'A' => 'Authentication of your Merchant ID and Password to the Directory Server Failed (see "What does a Payment Authentication Status of "A" mean?" on page 85).',
        # 'D' => 'Error communicating with the Directory Server, for example, the Payment Server could not connect to the directory server or there was a versioning mismatch.',
        # 'C' => 'The card type is not supported for authentication.',
        # 'M' => 'This indicates that attempts processing was used. Verification is marked with status M - ACS attempts processing used. Payment is performed with authentication. Attempts is when a cardholder has successfully passed the directory server but decides not to continue with the authentication process and cancels.',
        # 'S' => 'The signature on the response received from the Issuer could not be validated. This should be considered a failure.',
        # 'T' => 'ACS timed out. The Issuer\'s ACS did not respond to the Authentication request within the time out period.',
        # 'P' => 'Error parsing input from Issuer.',
        # 'I' => 'Internal Payment Server system error. This could be caused by a temporary DB failure or an error in the security module or by some error in an internal system.'
      }

    end
  end
end